name: Compile Payload Online

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build with PS4 Payload SDK
        uses: Scene-Collective/ps4-payload-sdk@v1
        with:
          app_path: '.'
          build_command: 'make'

      - name: Save Completed Binary
        uses: actions/upload-artifact@v4
        with:
          name: compiled-payload
          path: payload.bin
