name: Build PS4 Payload

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: Scene-Collective/ps4-payload-sdk@v1.0.0
        with:
          app_path: .
          build_command: make

      - name: Check payload
        run: |
          echo "Checking for payload.bin..."
          ls -lah payload.bin
          file payload.bin

      - name: Upload payload
        uses: actions/upload-artifact@v4
        with:
          name: ps4-payload
          path: ./payload.bin
          if-no-files-found: error
